name: Make scan.sh Executable

on:
  push:
    paths:
      - 'scan.sh'

jobs:
  chmod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make scan.sh executable
        run: chmod +x scan.sh

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Make scan.sh executable" || echo "No changes to commit"
          git push || echo "Nothing to push"
